# -*- coding: utf-8 -*-
"""Gemini - SES AI Task Classification - Probabilistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16b9bUJxDVoOVkrSWoruzm7zoevmr4tLN
"""

!pip install --upgrade google-generativeai



import google.generativeai as genai
import pandas as pd
import time
import json
import os
from google.colab import drive, userdata
from tqdm import tqdm

# Mount Google Drive
drive.mount('/content/drive')

# Get API Key from Colab Secrets
GEMINI_API_KEY = userdata.get('GOOGLE_API_KEY_1')

# Initialize Gemini client
genai.configure(api_key=GEMINI_API_KEY)

# Define task categories
task_categories = {
    "profcom": ["cteach", "cspeech", "cpersuad"],
    "coop": ["cteamwk", "clisten", "ccoop"],
    "writing": ["cwrite", "cwritesh", "cwritelg"],
    "reading": ["cread", "cshort", "clong"],
    "analytical": ["canalyse", "cfaults", "ccause", "csolutn"],
    "knowledge": ["cspecial", "cupto", "cideas"],
    "numeracy": ["cstats", "ccalca", "cpercent"],
    "physical": ["cstrength", "cstamina", "chands", "ctools"],
    "planning": ["cplanme", "cplanoth", "cmytime", "cahead", "cimpl"],
    "people": ["cmefeel", "cothfeel", "clookprt", "csoundprt"],
    "client": ["cpeople", "ccaring", "cselling", "cproduct"],
    "management": ["cmotivat", "cthings", "ccoach", "ccareers", "cfuture"]
}


# Task definitions
tasks = [
    {"handle": "cpeople", "description": "Dealing with people"},
    {"handle": "cteach", "description": "Instructing, training or teaching people, individually or in groups"},
    {"handle": "cspeech", "description": "Making speeches or presentations"},
    {"handle": "cpersuad", "description": "Persuading or influencing others"},
    {"handle": "cselling", "description": "Selling a product or service"},
    {"handle": "ccaring", "description": "Counselling, advising or caring for customers or clients"},
    {"handle": "cteamwk", "description": "Working with a team of people"},
    {"handle": "clisten", "description": "Listening carefully to colleagues"},
    {"handle": "ccoop", "description": "Cooperating with colleagues"},
    {"handle": "cstrength", "description": "Carrying, pushing or pulling heavy objects"},
    {"handle": "cstamina", "description": "Working for long periods on physical activities"},
    {"handle": "chands", "description": "Mending, repairing, assembling, constructing or adjusting things"},
    {"handle": "ctools", "description": "Knowledge of how to use or operate tools, equipment or machinery"},
    {"handle": "cproduct", "description": "Knowledge of particular products or services"},
    {"handle": "cspecial", "description": "Specialist knowledge or understanding"},
    {"handle": "cupto", "description": "Keeping up-to-date with and applying new knowledge to your job"},
    {"handle": "cfaults", "description": "Spotting problems or faults"},
    {"handle": "ccause", "description": "Working out the cause of problems or faults"},
    {"handle": "csolutn", "description": "Thinking of solutions to problems"},
    {"handle": "canalyse", "description": "Analysing complex problems in depth"},
    {"handle": "cideas", "description": "Developing new or improved work processes, products or services"},
    {"handle": "cplanme", "description": "Planning your own activities"},
    {"handle": "cplanoth", "description": "Planning the activities of others"},
    {"handle": "cmytime", "description": "Organising one's own time"},
    {"handle": "cahead", "description": "Thinking ahead"},
    {"handle": "cimpl", "description": "Developing plans to put new ideas into practice"},
    {"handle": "cread", "description": "Reading written information such as forms, notices or signs"},
    {"handle": "cshort", "description": "Reading short documents such as short reports, letters or emails"},
    {"handle": "clong", "description": "Reading long documents such as long reports, manuals, articles or books"},
    {"handle": "cwrite", "description": "Writing material such as forms, notices or signs"},
    {"handle": "cwritesh", "description": "Writing short documents (for example, short reports, letters or emails)"},
    {"handle": "cwritelg", "description": "Writing long documents with correct spelling and grammar (for example, long reports, manuals, articles or books)"},
    {"handle": "ccalca", "description": "Adding, subtracting, multiplying or dividing numbers (Note: Using a calculator or computer if necessary.)"},
    {"handle": "cpercent", "description": "Calculations using decimals, percentages or fractions (Note: Using a calculator or computer if necessary.)"},
    {"handle": "cstats", "description": "Calculations using more advanced mathematical or statistical procedures (Note: Using a calculator or computer if necessary.)"},
    {"handle": "cmotivat", "description": "Motivating the staff whom you manage or supervise"},
    {"handle": "cthings", "description": "Keeping a close control over resources"},
    {"handle": "ccoach", "description": "Coaching the staff whom you manage"},
    {"handle": "ccareers", "description": "Developing the careers of the staff whom you manage"},
    {"handle": "cfuture", "description": "Making strategic decisions about the future of your organisation"},
    {"handle": "cmefeel", "description": "Managing your own feelings"},
    {"handle": "cothfeel", "description": "Handling the feelings of other people"},
    {"handle": "clookprt", "description": "Looking the part"},
    {"handle": "csoundprt", "description": "Sounding the part"}
]

# Create a task lookup dictionary for quick access
task_lookup = {task["handle"]: task for task in tasks}

# Occupation groups to process
occupation_groups = ["11","12", "21", "22", "23", "24", "31", "32", "33", "34", "35", "41", "42", "51", "52", "53", "54", "61", "62", "71", "72", "81", "82", "91", "92"]

# Create a simple test function to verify API works
def test_gemini_api():
    try:
        model = genai.GenerativeModel('gemini-1.5-pro')
        response = model.generate_content("Respond with a simple JSON: {\"test\": \"successful\"}")
        print(f"API Test Response: {response.text}")
        return True
    except Exception as e:
        print(f"API Test Error: {e}")
        return False

# Function to get occupation details from file
def get_occupation_details(occupation_code, base_path="/content/drive/MyDrive/AI_Classification_Prompts/"):
    import glob
    file_path = f"{base_path}{occupation_code}_*.txt"  # Use glob pattern
    try:
        # Use glob to find the file
        files = glob.glob(file_path)
        if not files:
            print(f"No matching file found for occupation code {occupation_code}")
            return "No occupation details found."
        file_path = files[0]  # Take the first match

        with open(file_path, 'r') as f:
            content = f.read()
        return content
    except Exception as e:
        print(f"Error reading file for occupation code {occupation_code}: {e}")
        return "Error reading occupation details."

# Function to build prompt for a category of tasks and occupation with probability approach
def build_probability_prompt(category_name, task_handles, occupation_code):
    occupation_details = get_occupation_details(occupation_code)

    # Format task list for the prompt
    task_list = ""
    for handle in task_handles:
        if handle in task_lookup:
            task_list += f"{handle}: {task_lookup[handle]['description']}\n"

    # Add the examples section
    examples = """<examples>
<example>
<OCCUPATION_DETAILS>
# 24 Business, Media and Public Service Professionals

## Description
This sub-major group encompasses professionals who provide legal services, preside over judicial proceedings, manage financial information, offer business advice, and perform various roles in the public, welfare, regulatory, and voluntary sectors, as well as in media. These roles involve specialized knowledge and skills in their respective fields, often requiring professional qualifications and adherence to ethical standards.

## Common Work Activities (Background only. These are NOT the tasks to be classified)
* Providing legal advice and representation.
* Conducting financial analysis and reporting.
* Advising on business strategy and management.
* Managing projects and teams.
* Conducting research and analysis.
* Developing and implementing policies and procedures.
* Providing social work and welfare services.
* Working with offenders in the probation system.
* Providing spiritual guidance (clergy).
* Managing library and archival collections.
* Ensuring quality control and regulatory compliance.
* Working in journalism, public relations, and advertising.

## Related Job Titles
* Solicitor/Barrister/Judge
* Accountant
* Management Consultant
* Actuary/Economist/Statistician
* Social Worker
* Probation Officer
* Clergy Member
* Librarian/Archivist/Curator
* Quality Assurance Manager
* Environmental Health Officer
* Journalist/Editor
* Public Relations Officer
* Advertising Account Manager

## Existing Tools
* Computers and related hardware
* Telecommunications equipment
* Communication devices (mobile phones, tablets)
* Internet access (for research and communication)
* Standard productivity tools (word processing, spreadsheets, presentation software, email)
* Legal research databases (e.g., Westlaw, LexisNexis)
* Financial analysis software
* Statistical analysis software
* Project management software
* Customer Relationship Management (CRM) software (in some roles)
* Library and archival management systems
* Quality management systems
* Media production and editing software (for media professionals)
</OCCUPATION_DETAILS>
<TASK_HANDLE>
cpercent: Calculations using decimals, percentages or fractions (Note: Using a calculator or computer if necessary.)

</TASK_HANDLE>
<OCCUPATION_CODE>
24
</OCCUPATION_CODE>
<ideal_output>
<task_analysis>
a. Task summary: Performing calculations using decimals, percentages, or fractions in the context of financial analysis or related occupations.

b. Existing tools: Calculators, spreadsheets (e.g., Excel), and financial analysis software are commonly used for these calculations. These tools are purpose-built, highly optimized, immediately accessible, and provide instant results with minimal input effort.

c. Potential LLM capabilities:
- Performing calculations directly
- Explaining calculation steps
- Providing context or interpretation for results

d. Estimated time reduction:
E0: 0% (baseline)
E1: 5-10% (minimal reduction due to existing efficient tools and significant transaction costs)
E2: 15-20% (some reduction with integrated tools, but still constrained by interface overhead)
E3: Not applicable (image processing not relevant)

e. Arguments for each exposure level:
E0: Existing tools are highly efficient for these calculations and purpose-built with minimal friction
E1: LLMs could provide some assistance in complex calculations or explanations
E2: Integration with existing tools could streamline workflow

Arguments against each exposure level:
E0: LLMs might offer some benefits in certain specialized scenarios
E1: The incremental benefit over existing tools is minimal
- The overhead of opening a chat interface, formulating the query, waiting for the response, and verifying the answer often exceeds the time saved compared to using a calculator directly
- For routine calculations, the cognitive "context switch" to an LLM interface introduces inefficiency
- Verification is essential for calculations, adding another layer of overhead
E2: The integration might not provide significant time savings
- Even with integration, the need to verify results and the additional steps required would limit efficiency gains
E3: No relevant arguments, as image processing doesn't apply
</task_analysis>

{
  "task_handle": "cpercent",
  "occupation_code": "24",
  "probabilities": {
    "E0": 0.85,
    "E1": 0.10,
    "E2": 0.05,
    "E3": 0.00
  },
  "justification": "Existing tools like calculators and spreadsheets are already highly efficient for these calculations, offering minimal opportunity for significant time savings from LLMs. The overhead of interfacing with an LLM (query formulation, waiting for responses, verification) often negates potential time savings for straightforward calculations. For routine mathematical operations, dedicated tools remain significantly faster and more practical."
}
</ideal_output>
</example>
<example>
<OCCUPATION_DETAILS>
# 81 Process, Plant and Machine Operatives

## Description
This sub-major group encompasses individuals who operate and maintain machinery and equipment used in various industrial processes, including manufacturing, food processing, chemical processing, metalworking, and construction. These roles require technical skills, knowledge of machinery operation, and often involve repetitive tasks and adherence to safety procedures.

## Common Work Activities (Background only. These are NOT the tasks to be classified)
* Operating and attending machinery to process food, beverages, textiles, chemicals, and other materials.
* Operating plant and machinery to produce paper, wood, and related products.
* Extracting coal and other minerals.
* Operating power generation and water treatment systems.
* Operating metalworking machinery.
* Assembling and inspecting products.
* Performing routine maintenance and repairs on machinery and equipment.
* Constructing and maintaining roads, railways, and other infrastructure.
* Erecting and dismantling scaffolding.

## Related Job Titles
* Food, Drink, and Tobacco Process Operative
* Glass and Ceramics Process Operative
* Textile Process Operative
* Chemical Process Operative
* Rubber/Plastics Process Operative
* Metal Making and Treating Process Operative
* Electroplater
* Paper and Wood Machine Operative
* Coal Mine Operative
* Quarry Worker
* Energy Plant Operative
* Metal Working Machine Operative
* Water and Sewerage Plant Operative
* Printing Machine Assistant
* Assembler (Electrical, Electronic, Vehicles, Metal Goods)
* Routine Inspector/Tester
* Weigher/Grader/Sorter
* Tyre/Exhaust/Windscreen Fitter
* Scaffolder/Rigger
* Construction Operative (Road, Rail, Maintenance)

## Existing Tools
* Computers and related hardware (for some roles, e.g., CNC machinists, process control)
* Communication devices (mobile phones, two-way radios)
* Hand tools (specific to the trade)
* Power tools (specific to the trade)
* Machinery and equipment specific to the industry and process (e.g., food processing equipment, textile machinery, printing presses, metalworking machines, construction equipment)
* Measuring instruments (e.g., gauges, calipers, micrometers)
* Testing equipment (specific to the product or process)
* Safety equipment (e.g., gloves, goggles, hard hats, respirators)
</OCCUPATION_DETAILS>
<TASK_HANDLE>
cadjust: Adjust, clean, or repair products or processing equipment to correct defects found during inspections.
</TASK_HANDLE>
<OCCUPATION_CODE>
81
</OCCUPATION_CODE>
<ideal_output>
<task_analysis>
a. Task summary: Adjusting, cleaning, or repairing products or processing equipment to correct defects found during inspections in a manufacturing or industrial setting.

b. Existing tools: Hand tools, power tools, measuring instruments, testing equipment, cleaning kits, and specialized repair kits.

c. Potential LLM capabilities:
- Providing step-by-step instructions for repairs or adjustments
- Offering troubleshooting guidance
- Explaining technical diagrams or manuals

d. Estimated time reduction:
E0: 0% (baseline)
E1: 5-10% (minimal reduction due to physical nature of task)
E2: 10-20% (potential reduction with integrated tools and AR)
E3: 15-25% (potential reduction with advanced image recognition)

e. Arguments for each exposure level:
E0: The task is primarily physical and requires hands-on work
E1: LLMs could provide some guidance or instructions
E2: Integration with AR could provide real-time assistance
E3: Image recognition could help identify defects or guide repairs

Arguments against each exposure level:
E0: LLMs might offer some benefits in certain scenarios
E1: The physical nature of the task limits LLM impact
E2: AR integration might not be practical in all work environments
E3: Image capabilities might not significantly reduce time for experienced workers
</task_analysis>

{
  "task_handle": "cadjust",
  "occupation_code": "81",
  "probabilities": {
    "E0": 0.80,
    "E1": 0.10,
    "E2": 0.07,
    "E3": 0.03
  },
  "justification": "The task primarily requires physical actions, limiting the impact of LLMs. While LLMs could provide guidance, the hands-on nature of the work means significant time reduction is unlikely."
}
</ideal_output>
</example>
<example>
<OCCUPATION_DETAILS>
# 21 Science, Research, Engineering and Technology Professionals

## Description
This sub-major group encompasses professionals engaged in scientific research and consultancy, technical supervision of engineering projects, IT and telecommunications consultancy and development, environmental conservation, and research and development management.  These roles involve applying specialized knowledge and skills in their respective fields to solve problems, develop new technologies, and advise on best practices.

## Common Work Activities (Background only. These are NOT the tasks to be classified)
* Conducting research and experiments.
* Analyzing data and interpreting results.
* Developing and implementing technical solutions.
* Providing expert advice and consultancy.
* Managing projects and teams.
* Ensuring compliance with regulations and standards.
* Presenting findings and recommendations.
* Designing and testing systems and prototypes.

## Related Job Titles
* Chemist
* Biologist
* Physicist
* Engineer (Civil, Mechanical, Electrical, etc.)
* IT Consultant
* Software Developer
* Conservation Officer
* Environmental Scientist
* Research and Development Manager

## Existing Tools
* Computers and related hardware
* Telecommunications equipment
* Communication devices (mobile phones, tablets)
* Internet access (for research and communication)
* Standard productivity tools (word processing, spreadsheets, presentation software, email)
* Laboratory equipment (specific to the scientific discipline)
* CAD software (for engineering and design)
* Programming languages and development environments (for IT professionals)
* Statistical analysis software
* Geographic Information Systems (GIS) (for environmental and some social science roles)
* Project management software
* Specialized scientific software (e.g., simulation software, data analysis packages)
</OCCUPATION_DETAILS>
<TASK_HANDLE>
capply: Apply theoretical expertise and innovation to create or apply new technology, such as adapting principles for applying computers to new uses.
</TASK_HANDLE>
<OCCUPATION_CODE>
21
</OCCUPATION_CODE>
<ideal_output>
<task_analysis>
a. Task summary: Applying theoretical expertise and innovation to create or apply new technology, such as adapting principles for applying computers to new uses in a computer and mathematical occupation.

b. Existing tools: Research databases, scientific literature, programming IDEs, simulation software, and collaborative platforms.

c. Potential LLM capabilities:
- Generating novel ideas based on existing principles
- Providing context and connections between different technological concepts
- Assisting in code generation for new applications
- Summarizing and synthesizing relevant research

d. Estimated time reduction:
E0: 0% (baseline)
E1: 25-40% (significant reduction in ideation and research phases)
E2: 35-50% (additional reduction with integrated development tools)
E3: 40-55% (further reduction with advanced image and data processing)

e. Arguments for each exposure level:
E0: The task requires high-level expertise and creativity
E1: LLMs can significantly assist in idea generation and research
E2: Integration with development tools could streamline implementation
E3: Advanced image and data processing could enhance analysis and testing

Arguments against each exposure level:
E0: The task aligns well with LLM capabilities in knowledge synthesis
E1: Human expertise is still crucial for validating and refining ideas
E2: Integration might not cover all aspects of the innovation process
E3: Image capabilities might not be relevant for all types of technological innovation
</task_analysis>

{
  "task_handle": "capply",
  "occupation_code": "21",
  "probabilities": {
    "E0": 0.10,
    "E1": 0.50,
    "E2": 0.30,
    "E3": 0.10
  },
  "justification": "LLMs can directly assist in generating novel ideas and adapting existing principles, likely reducing time by over 25%. Integration with development tools could further enhance efficiency."
}
</ideal_output>
</example>
<example>
<OCCUPATION_DETAILS>
# 22 Health Professionals

## Description
This sub-major group comprises professionals who provide medical treatments and diagnoses for humans and animals, conduct medical research, dispense pharmaceuticals, offer therapeutic treatments, and administer nursing and midwifery care.  These roles involve direct patient care, research, and specialized medical services, often working collaboratively within healthcare teams.

## Common Work Activities (Background only. These are NOT the tasks to be classified)
* Diagnosing illnesses and injuries.
* Prescribing and administering treatments.
* Conducting medical tests and interpreting results.
* Providing preventative care and advice.
* Performing surgery and other medical procedures.
* Dispensing medications and counseling on their use.
* Providing therapeutic treatments (e.g., physiotherapy, occupational therapy).
* Administering nursing and midwifery care.
* Conducting research and participating in clinical trials.

## Related Job Titles
* Medical Practitioner (Doctor, General Practitioner, Surgeon, etc.)
* Psychologist
* Pharmacist
* Ophthalmic Optician
* Dental Practitioner
* Veterinarian
* Radiographer
* Physiotherapist
* Occupational Therapist
* Registered Nurse
* Midwife

## Existing Tools
* Computers and related hardware
* Telecommunications equipment
* Communication devices (mobile phones, tablets)
* Internet access (for research and communication)
* Standard productivity tools (word processing, spreadsheets, presentation software, email)
* Medical diagnostic equipment (e.g., X-ray machines, MRI scanners, ultrasound)
* Surgical instruments
* Laboratory equipment (for testing and analysis)
* Patient record systems (electronic health records - EHRs)
* Dispensing software (for pharmacies)
* Therapeutic equipment (specific to the therapy provided)
* Veterinary-specific tools and equipment
</OCCUPATION_DETAILS>
<TASK_HANDLE>
cprescribe: Prescribe medication such as antihistamines, antibiotics, and nasal, oral, topical, or inhaled glucocorticosteroids.
</TASK_HANDLE>
<OCCUPATION_CODE>
22
</OCCUPATION_CODE>
<ideal_output>
<task_analysis>
a. Task summary: Prescribing medication such as antihistamines, antibiotics, and various forms of glucocorticosteroids in a healthcare setting.

b. Existing tools: Electronic Health Records (EHR) systems, e-prescribing software, medical reference databases (e.g., UpToDate, Epocrates), and clinical guidelines.

c. Potential LLM capabilities:
- Suggesting potential diagnoses based on symptoms
- Providing information on drug interactions and dosages
- Assisting in writing prescriptions and case notes
- Summarizing patient history and relevant medical literature

d. Estimated time reduction:
E0: 0% (baseline)
E1: 15-25% (some reduction in information gathering and documentation)
E2: 20-35% (reduction with integrated systems, constrained by verification requirements)
E3: 25-40% (additional reduction with image analysis, limited by safety considerations)

e. Arguments for each exposure level:
E0: Prescribing requires expert medical judgment and legal responsibility
E1: LLMs can assist in information retrieval and documentation
E2: Integration with medical systems could streamline the prescribing process
E3: Image analysis could aid in diagnosis and treatment planning

Arguments against each exposure level:
E0: LLMs offer significant potential to assist in various aspects of prescribing
E1: Direct LLM use faces ethical and liability concerns requiring substantial verification
E2: Regulatory requirements and medical liability create significant verification overhead
E3: Clinical validation of AI image interpretation is mandatory for patient safety
</task_analysis>

{
  "task_handle": "cprescribe",
  "occupation_code": "22",
  "probabilities": {
    "E0": 0.20,
    "E1": 0.25,
    "E2": 0.40,
    "E3": 0.15
  },
  "justification": "While prescribing relies on physician's judgment, LLM integration with medical systems could reduce time spent on information gathering and documentation. However, ethical requirements, regulatory constraints, and medical liability concerns create substantial verification overhead that limits potential time savings in this safety-critical domain."
}
</ideal_output>
</example>
<example>
<OCCUPATION_DETAILS>
# 35 Business and Public Service Associate Professionals

## Description
This sub-major group encompasses individuals who perform a wide range of support functions in business, finance, sales, marketing, public services, human resources, training, and regulatory compliance. These roles often involve specialized knowledge, administrative skills, and client/customer interaction.

## Common Work Activities (Background only. These are NOT the tasks to be classified)
* Controlling air and sea traffic.
* Providing administrative support in legal settings.
* Performing financial tasks (estimating, valuing, brokering, underwriting, advising).
* Purchasing goods and materials.
* Providing technical sales advice.
* Conducting market research.
* Managing property transactions.
* Organizing conferences and events.
* Managing human resources and industrial relations.
* Providing vocational training and career guidance.
* Inspecting for compliance with standards and regulations.
* Promoting health and safety in the workplace.

## Related Job Titles
* Air Traffic Controller
* Aircraft Pilot/Flight Engineer
* Ship/Hovercraft Officer
* Legal Associate Professional
* Estimator/Valuer/Assessor
* Broker
* Insurance Underwriter
* Financial Adviser/Analyst
* Buyer/Procurement Officer
* Business Sales Executive
* Marketing Associate Professional
* Estate Agent/Auctioneer
* Sales Account Manager
* Conference/Exhibition Organizer
* Public Services Associate Professional
* Human Resources Officer
* Vocational Trainer/Instructor
* Careers Adviser
* Inspector of Standards and Regulations
* Health and Safety Officer

## Existing Tools
* Computers and related hardware
* Telecommunications equipment
* Communication devices (mobile phones, tablets)
* Internet access (for research and communication)
* Standard productivity tools (word processing, spreadsheets, presentation software, email)
* Specialized software for finance, accounting, CRM, and project management
* Navigation and communication equipment (for transport roles)
* Legal research databases
* Market research tools and software
* Property management software
* Health and safety monitoring equipment
</OCCUPATION_DETAILS>
<TASK_HANDLE>
cnegotiate: Negotiate purchases or contracts
</TASK_HANDLE>
<OCCUPATION_CODE>
35
</OCCUPATION_CODE>
<ideal_output>
<task_analysis>
a. Task summary:  Discussing and finalizing terms (including price, scope, timeline, and legal provisions) with vendors, suppliers, or clients. It is a core responsibility among Business and Public Service Associate Professionals (occupation code 35), particularly in roles like Buyer/Procurement Officer, Sales Account Manager, and Marketing Associate Professional. Effective negotiation requires knowledge of market conditions, strategic communication, and an understanding of legal and organizational constraints.

b. Existing tools: Computers and related hardware for drafting and tracking negotiation terms, Telecommunications equipment (e.g., phones, videoconferencing tools) for conducting real-time negotiations, Standard productivity software (word processors, spreadsheets, email) for managing proposals and contracts, Specialized software (finance, accounting, CRM, project management) to track contract status, budgets, and supplier information, Legal research databases to check for compliance and standard contractual clauses, Market research tools to compare prices and offerings.

c. Potential LLM capabilities:
- Drafting and refining contract language.
- Summarizing complex contractual documents or negotiation notes, highlighting changes or key points of contention.
- Proposing negotiation strategies or alternative contractual clauses based on historical data or best practices.
- Suggesting consistent formatting or standardized clauses to ensure compliance with common legal frameworks.
- Providing data-driven arguments or talking points for price, delivery, or warranty negotiations.

d. Estimate time reduction:
E0 (No Exposure): Little to no time savings if LLMs are absent or unused. Negotiation remains a manual process of drafting and discussion.
E1 (Direct Exposure): Approximately ≥25% time reduction if an LLM assists in drafting and summarizing documents or generating strategic points, even without deep software integration.
E2 (Exposure via Imaginable LLM-Powered Applications): Greater time savings (≥25% and potentially higher) if combined with specialized negotiation software that integrates automated data analysis, contract drafting, and tracking.
E3 (Exposure given Image Capabilities): Minimal relevance for image-based features, as most negotiations involve text-based or verbal content.

e. Provide arguments for and against each exposure level:
E0 (No Exposure):
– For: Negotiations demand human judgment, persuasion, and relationship-building, which may not be fully automated.
– Against: LLMs can accelerate or improve parts of the process, such as drafting or summarizing contracts, thus reducing manual effort.

E1 (Direct Exposure):
– For: LLM tools can transform raw meeting transcripts or basic negotiation notes into cohesive summaries, generate potential clauses, and accelerate routine contract language tasks.
– Against: Negotiation's interpersonal aspect still requires a human to interpret social cues, read body language, and adapt in real-time.

E2 (Exposure via Imaginable LLM-Powered Applications):
– For: Deeper integration into contract-management or negotiation software could automate routine steps (e.g., cross-referencing standard clauses, analyzing competitor pricing) and streamline negotiations.
– Against: Full reliance on integrated systems still cannot entirely replace the nuance and trust-building components of successful negotiations, especially in high-stakes or relationship-based contexts.

E3 (Exposure given Image Capabilities):
– For: Some specialized use cases might involve scanning and interpreting paper contracts, but this is a minor portion of modern negotiations, so not a major factor overall.
– Against: Negotiations are primarily text-based (digital) and involve verbal interactions, limiting the utility of purely image-based capabilities.
</task_analysis>

{
"task_handle": "cnegotiate",
"occupation_code": "35",
"probabilities": {
"E0": 0.10,
"E1": 0.30,
"E2": 0.60,
"E3": 0.00
},
"justification": "Negotiating purchases or contracts still requires substantial human judgment and relationship-building, so there's some probability (E0) that LLMs may not drastically reduce time in interpersonal aspects. However, LLMs can provide significant direct assistance (E1) through document drafting and summarization. With deeper automation and specialized negotiation platforms, there's even more potential for time savings (E2). Image-based features offer negligible value for primarily text-based negotiations (E3)."
}
</ideal_output>
</example>
</examples>"""

    prompt = f"""{examples}

Your goal is to assess the probability of different levels of AI exposure for each task within a specific occupation category.

Before we begin, please review the following occupation details:
<occupation_details>
{occupation_details}
</occupation_details>


You will analyze a category of related tasks for Occupation Code {occupation_code}. For each task, determine the probability of different AI exposure levels.

<category_name>
{category_name}
</category_name>

You will analyze the following list of tasks:
<task_list>
{task_list}
</task_list>

Instructions:
1. Analyze each task in the context of the occupation details provided.
2. Consider how an average worker in this occupation would typically perform each task using existing tools.
3. Assess how LLMs could potentially assist with each task, focusing on new capabilities beyond existing tools.
4. For EACH TASK, calculate the probability of it falling into each of the following AI exposure levels:

   - E0: No Exposure (LLMs do not meaningfully reduce time by 25% or more)
   - E1: Direct Exposure (LLMs alone can reduce time by at least 25%)
   - E2: Exposure via Imaginable LLM-Powered Applications (LLMs + additional software could reduce time by at least 25%)
   - E3: Exposure given Image Capabilities (Image processing significantly reduces time by 25% or more)

5. Provide a brief justification for each probability distribution.

In your analysis for each task, include:
a. Task summary in the context of the occupation
b. Existing tools typically used for this task
c. Potential LLM capabilities that could assist with the task
d. Arguments for and against each exposure level

First provide a high-level analysis of the entire category in this occupation context.
Then analyze each task individually, giving probability distributions that sum to 1.0 (expressed as decimals).

Output Format:
Provide your response in the following JSON format:

```json
[
  {{
    "task_handle": "task1_handle",
    "occupation_code": "{occupation_code}",
    "task_description": "Description of task 1",
    "probabilities": {{
      "E0": 0.XX,
      "E1": 0.XX,
      "E2": 0.XX,
      "E3": 0.XX
    }},
    "justification": "One sentence justification for probabilities"
  }},
  {{
    "task_handle": "task2_handle",
    "occupation_code": "{occupation_code}",
    "task_description": "Description of task 2",
    "probabilities": {{
      "E0": 0.XX,
      "E1": 0.XX,
      "E2": 0.XX,
      "E3": 0.XX
    }},
    "justification": "One sentence justification for probabilities"
  }},
  ...
]

Remember to consider the incremental impact of LLMs beyond pre-existing tools and technologies, and focus on the potential 25% or more time reduction for each exposure level.
"""
    return prompt

# Function to classify a task category using Gemini API
def classify_task_category_with_probabilities(category_name, task_handles, occupation_code, max_retries=2):
    prompt = build_probability_prompt(category_name, task_handles, occupation_code)

    # Initialize the Gemini model
    model = genai.GenerativeModel('gemini-1.5-pro',
                                  generation_config=genai.GenerationConfig(
                                      temperature=0.2,
                                      max_output_tokens=4096,
                                      top_p=0.95
                                  ))

    for attempt in range(max_retries + 1):
        try:
            print(f"Classifying {category_name} category for occupation {occupation_code} (Attempt {attempt+1})")

            # Generate content with the Gemini model
            response = model.generate_content(prompt)
            response_text = response.text

            # Extract JSON from response
            try:
                # First try to find JSON in code blocks
                if "```json" in response_text and "```" in response_text.split("```json", 1)[1]:
                    json_str = response_text.split("```json", 1)[1].split("```", 1)[0].strip()
                    task_data = json.loads(json_str)
                    return task_data

                # If that fails, try to extract JSON directly
                elif "[" in response_text and "]" in response_text:
                    start_idx = response_text.find("[")
                    end_idx = response_text.rfind("]") + 1
                    json_str = response_text[start_idx:end_idx]
                    task_data = json.loads(json_str)
                    return task_data

                else:
                    print("No JSON found in response")
                    print(f"Response text: {response_text[:200]}...")
                    if attempt < max_retries:
                        time.sleep(5 * (attempt + 1))  # Exponential backoff
                        continue
            except json.JSONDecodeError as e:
                print(f"JSON parsing error: {e}")
                print(f"Response text: {response_text[:200]}...")
                if attempt < max_retries:
                    time.sleep(5 * (attempt + 1))  # Exponential backoff
                    continue

        except Exception as e:
            print(f"API call error: {e}")
            if attempt < max_retries:
                time.sleep(5 * (attempt + 1))  # Exponential backoff
                continue

    # If all retries fail, return a fallback response with error indicators for each task
    return [
        {
            "task_handle": handle,
            "occupation_code": occupation_code,
            "task_description": task_lookup[handle]["description"] if handle in task_lookup else "Unknown task",
            "probabilities": {
                "E0": 0.0,
                "E1": 0.0,
                "E2": 0.0,
                "E3": 0.0
            },
            "justification": "ERROR: Failed to get response"
        }
        for handle in task_handles
    ]

# Main function for processing all tasks and occupations
def main():
  # Test API connection
  if not test_gemini_api():
    print("API test failed. Please check your API key and connection.")
    return

  # Create output directory if it doesn't exist
  output_dir = '/content/drive/MyDrive/AI_Classification_Outputs'
  os.makedirs(output_dir, exist_ok=True)

  # Define output path - updated to indicate probability-based approach
  output_path = f'{output_dir}/job_task_probabilities_gemini_r3.csv'

  # Load existing results if any
  if os.path.exists(output_path):
      print(f"Loading existing results from {output_path}")
      existing_df = pd.read_csv(output_path)
      results = existing_df.to_dict('records')
      processed = set((r['occupation_code'], r['task_handle']) for r in results)
      print(f"Loaded {len(results)} existing results")
  else:
      results = []
      processed = set()

  # Calculate total number of tasks to process
  total_tasks = sum(len(task_handles) for task_handles in task_categories.values()) * len(occupation_groups)
  remaining_task_count = total_tasks - len(processed)

  print(f"Total tasks to process: {total_tasks}")
  print(f"Already processed: {len(processed)}")
  print(f"Remaining tasks: {remaining_task_count}")

  # Process each occupation
  with tqdm(total=remaining_task_count, desc="Processing Task Categories") as pbar:
      for occupation_code in occupation_groups:
          print(f"\nProcessing occupation: {occupation_code}")

          # Process each task category for this occupation
          for category_name, task_handles in task_categories.items():
              # Check if any tasks in this category need processing for this occupation
              tasks_to_process = [handle for handle in task_handles
                                  if (occupation_code, handle) not in processed]

              if not tasks_to_process:
                  print(f"  All tasks in category {category_name} already processed for occupation {occupation_code}")
                  continue

              print(f"  Processing category: {category_name} ({len(tasks_to_process)} tasks)")

              # Process the task category with probabilities approach
              task_results = classify_task_category_with_probabilities(category_name, tasks_to_process, occupation_code)

              if task_results:
                  # Ensure each result has the right occupation code
                  for result in task_results:
                      result['occupation_code'] = occupation_code
                      task_handle = result['task_handle']

                      # Add to results and mark as processed
                      results.append(result)
                      processed.add((occupation_code, task_handle))

                  # Update progress bar
                  pbar.update(len(tasks_to_process))

                  # Save intermediate results
                  temp_df = pd.DataFrame(results)
                  # Flatten the probabilities structure for CSV storage
                  if 'probabilities' in temp_df.columns:
                      for e_level in ['E0', 'E1', 'E2', 'E3']:
                          temp_df[f'prob_{e_level}'] = temp_df['probabilities'].apply(
                              lambda x: x.get(e_level, 0) if isinstance(x, dict) else 0
                          )
                      temp_df = temp_df.drop('probabilities', axis=1)
                  temp_df.to_csv(output_path, index=False)

                  # Add a delay to avoid rate limits
                  time.sleep(2)

  # Final save and report
  df = pd.DataFrame(results)
  # Flatten the probabilities structure for CSV storage
  if 'probabilities' in df.columns:
      for e_level in ['E0', 'E1', 'E2', 'E3']:
          df[f'prob_{e_level}'] = df['probabilities'].apply(
              lambda x: x.get(e_level, 0) if isinstance(x, dict) else 0
          )
      df = df.drop('probabilities', axis=1)

  df.to_csv(output_path, index=False)
  print(f"\nFinal results saved to: {output_path}")
  print(f"Total records: {len(df)}")

  # Calculate statistics
  if 'prob_E0' in df.columns:
      # Calculate average probabilities for each exposure level
      avg_probs = {
          'E0': df['prob_E0'].mean(),
          'E1': df['prob_E1'].mean(),
          'E2': df['prob_E2'].mean(),
          'E3': df['prob_E3'].mean()
      }

      print("\nAverage Probabilities by Exposure Level:")
      for level, avg in avg_probs.items():
          print(f"{level}: {avg:.4f}")

      # Create a simple bar chart of average probabilities
      try:
          import matplotlib.pyplot as plt

          plt.figure(figsize=(10, 6))
          plt.bar(avg_probs.keys(), avg_probs.values(), color='skyblue')
          plt.title('Average AI Exposure Probabilities')
          plt.xlabel('Exposure Category')
          plt.ylabel('Average Probability')
          plt.ylim(0, 1)
          plt.tight_layout()

          # Save chart
          chart_path = f'{output_dir}/avg_exposure_probabilities_gemini.png'
          plt.savefig(chart_path)
          print(f"Chart saved to: {chart_path}")

          plt.show()
      except Exception as e:
          print(f"Error creating chart: {e}")

# Run the main function
if __name__ == "__main__":
    main()