# -*- coding: utf-8 -*-
"""GAISI_Critic_Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QeN5fXE6u2GJYQCX15fi95wA-VwLTeXh

# CELL 1: Setup and Configuration
"""

# =============================================================================
# CELL 1: Setup and Configuration
# =============================================================================

# Install SDK (uncomment if needed)
# !pip install -q -U "google-genai>=1.34.0"

import json
import time
import logging
import csv
import re
from pathlib import Path
from datetime import datetime
import pandas as pd

from google.colab import drive, userdata
from google import genai
from google.genai import types

# Mount drive and set paths
drive.mount('/content/drive')
BASE_PATH = Path('/content/drive/My Drive/AI_CLASSIFICATION')
INPUT_DIR = BASE_PATH / "Inputs"
OUTPUT_DIR = BASE_PATH / "Outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Source files (same as classification step)
DESCRIPTIONS_FILE = INPUT_DIR / "sug_codes_descriptions.clean.csv"
TASKS_FILE = INPUT_DIR / "sugs_to_tasks.csv"

# Classification output to review
CLASSIFICATIONS_FILE = OUTPUT_DIR / "gaisi_classifications_20251230.edit.csv"

# Reviewer outputs
BATCH_REQUESTS_FILE = OUTPUT_DIR / "critic_batch_requests_1408.jsonl"
JOB_STATE_FILE = OUTPUT_DIR / "critic_job_state_1408.json"
RESULTS_FILE = OUTPUT_DIR / "critic_batch_results.jsonl"
PARSED_CRITIC_FILE = OUTPUT_DIR / "critic_reviews.csv"
FINAL_MERGED_FILE = OUTPUT_DIR / "gaisi_classifications_reviewed.csv"

# Column mappings
DESC_COLS = {'code': 'sugcode', 'title': 'sugtitle', 'description': 'sugdescription'}
TASK_COLS = {'code': 'sugcode', 'id': 'taskid', 'statement': 'task'}

# Model config (same as classification)
MODEL_ID = "gemini-2.5-pro"
THINKING_BUDGET = 1600

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(message)s")
logger = logging.getLogger(__name__)

# Initialize client
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY_1')
client = genai.Client(api_key=GOOGLE_API_KEY)

print(f"Model: {MODEL_ID}")
print(f"Thinking budget: {THINKING_BUDGET}")
print(f"Classifications to review: {CLASSIFICATIONS_FILE}")
print(f"Output dir: {OUTPUT_DIR}")

"""# CELL 2: Critic System Prompt"""

# =============================================================================
# CELL 2: Critic System Prompt
# =============================================================================

CRITIC_SYSTEM_PROMPT = """You are a critical AI reviewer auditing LLM exposure classifications. Your role is adversarial: identify weaknesses, inconsistencies, and unsupported claims.

You will receive:
<occupation_details>: The occupation being classified
<task_list>: The original tasks presented to the classifier
<classification_output>: A table with generated task-level exposure probabilities (E0–E3) and justifications

the exposure levels represent:
-   **E0: No Exposure**: LLMs are unlikely to reduce task completion time by 25%. Existing tools are highly efficient, or the task is inherently physical, interpersonal, or requires high-stakes human judgment.
-   **E1: Direct Exposure**: Using an LLM via a chat interface or console (e.g. ChatGPT or Open AI playground) can decrease the time required to complete the task by at 25%.
-   **E2: Integrated Exposure**: An LLM integrated into other software (e.g., an "AI assistant" or "Co-pilot" in a specific application) or hardware (robotics) can reduce task time by 25% or more.
-   **E3: Image Exposure**: LLM-based image generation or analysis can reduce task time by at least 25%.

# Evaluation Criteria
Attack each classification on three fronts:

## 1. Justification–Distribution Alignment
Do the assigned probabilities follow logically from the stated justification? Flag mismatches, for example:
Justification emphasises physical or interpersonal demands, but E0 < 0.5
Justification claims strong LLM potential, but E1 + E2 < 0.5
Probability mass spread thinly across levels without justification for uncertainty

## 2. Prompt Compliance
Does the justification demonstrate faithful application of the classification rubric?

- Existing-tools test: Does the justification acknowledge what workers already accomplish with current non-AI software, hardware, or standard practice? Flag if the rater credits LLMs for gains achievable with existing non-AI tools such as templates, macros, search engines, dictation software, or standard databases.

- 25% threshold test: Is the claimed time reduction plausible and specific? Flag vague appeals like "LLMs could assist" without a concrete mechanism that clears the 25% bar. The justification must identify what the LLM does and why it saves meaningful time.

## 3. Intra-Occupation Consistency
After reviewing individual rows, assess cross-task coherence:
Similar tasks rated similarly: Tasks with comparable cognitive demands, output types, or LLM applicability should receive comparable probability distributions. Flag unexplained divergence.
Task hierarchy respected: Higher-level tasks (planning, strategising, synthesising) and their constituent sub-tasks (executing steps, recording outputs) should have logically related ratings. Flag if a sub-task is rated as more exposed than its parent without justification.

# Output Format: soccode, taskid, confidence, critique
YOU MUST Provide your review as a CSV table with one row per task:
{soccode}, {taskid}, [0,1], "One-sentence critique or 'No issues'"

confidence: Your confidence that the original rating is defensible.
1 = Fully defensible or minor issues; no evaluation criterion is violated; probabilities and justification are consistent, rubric-compliant, and coherent with related tasks
0 = Material concerns; one or more evaluation criterion are violated
critique: One sentence identifying the specific weakness, or "No issues" if no evaluation criterion is violated.

Do not include a header row. Output ONLY the data rows; NOTHING else.
"""

print(f"Critic system prompt: {len(CRITIC_SYSTEM_PROMPT)} characters")

"""# CELL 3: Load Data"""

# =============================================================================
# CELL 3: Load Data
# =============================================================================

def load_source_data():
    """Load occupation descriptions and task statements."""

    # Load descriptions
    logger.info(f"Loading: {DESCRIPTIONS_FILE.name}")
    desc_df = pd.read_csv(DESCRIPTIONS_FILE, dtype=str)
    desc_df = desc_df.rename(columns={
        DESC_COLS['code']: 'sug_code',
        DESC_COLS['title']: 'title',
        DESC_COLS['description']: 'description'
    })
    desc_df['sug_code'] = desc_df['sug_code'].str.strip()

    # Load tasks
    logger.info(f"Loading: {TASKS_FILE.name}")
    tasks_df = pd.read_csv(TASKS_FILE, dtype=str)
    tasks_df = tasks_df.rename(columns={
        TASK_COLS['code']: 'sug_code',
        TASK_COLS['id']: 'task_id',
        TASK_COLS['statement']: 'task_statement'
    })
    tasks_df['sug_code'] = tasks_df['sug_code'].str.strip()

    return desc_df, tasks_df


def load_classifications():
    """Load the classification output to be reviewed."""

    logger.info(f"Loading classifications: {CLASSIFICATIONS_FILE.name}")
    class_df = pd.read_csv(CLASSIFICATIONS_FILE, dtype=str)

    # Standardize column names
    class_df.columns = class_df.columns.str.strip().str.lower()
    class_df['sugcode'] = class_df['sugcode'].str.strip()
    class_df['taskid'] = class_df['taskid'].str.strip()

    logger.info(f"Loaded {len(class_df)} classifications across {class_df['sugcode'].nunique()} occupations")

    return class_df


# Load all data
desc_df, tasks_df = load_source_data()
class_df = load_classifications()

print(f"\nDescriptions: {len(desc_df)} occupations")
print(f"Tasks: {len(tasks_df)} task-occupation pairs")
print(f"Classifications: {len(class_df)} rows")

"""# CELL 4: Build Critic Prompts and Batch Requests"""

# =============================================================================
# CELL 4: Build Critic Prompts and Batch Requests
# =============================================================================

def build_critic_prompt(sug_code: str, title: str, description: str,
                        tasks: list, classifications: list) -> str:
    """Build user prompt for critic review of a single occupation."""

    # Occupation details block
    occupation_block = f"""occupation_code: {sug_code}
occupation_title: {title}
occupation_description: {description}"""

    # Task list (original tasks)
    task_lines = "\n".join(f"{t['task_id']}\t{t['task_statement']}" for t in tasks)

    # Classification output table
    class_header = "taskid, e0, e1, e2, e3, justification"
    class_lines = "\n".join(
        f"{c['taskid']}, {c['e0']}, {c['e1']}, {c['e2']}, {c['e3']}, \"{c['justification']}\""
        for c in classifications
    )

    return (
        f"<occupation_details>\n{occupation_block}\n</occupation_details>\n\n"
        f"<task_list>\n{task_lines}\n</task_list>\n\n"
        f"<classification_output>\n{class_header}\n{class_lines}\n</classification_output>"
    )


def generate_critic_batch_requests(desc_df: pd.DataFrame, tasks_df: pd.DataFrame,
                                    class_df: pd.DataFrame, output_path: Path) -> int:
    """Generate JSONL file with batch requests for critic review."""

    request_count = 0
    skipped = []

    with open(output_path, 'w') as f:
        for sug_code in class_df['sugcode'].unique():
            # Get occupation details
            desc_row = desc_df[desc_df['sug_code'] == sug_code]
            if desc_row.empty:
                skipped.append((sug_code, 'no description'))
                continue
            desc_row = desc_row.iloc[0]

            # Get original tasks
            occ_tasks = tasks_df[tasks_df['sug_code'] == sug_code]
            if occ_tasks.empty:
                skipped.append((sug_code, 'no tasks'))
                continue
            tasks = [
                {'task_id': r['task_id'], 'task_statement': r['task_statement']}
                for _, r in occ_tasks.iterrows()
            ]

            # Get classifications for this occupation
            occ_class = class_df[class_df['sugcode'] == sug_code]
            classifications = [
                {
                    'taskid': r['taskid'],
                    'e0': r['e0'],
                    'e1': r['e1'],
                    'e2': r['e2'],
                    'e3': r['e3'],
                    'justification': r['justification']
                }
                for _, r in occ_class.iterrows()
            ]

            # Build prompt
            user_prompt = build_critic_prompt(
                sug_code,
                desc_row['title'],
                desc_row['description'],
                tasks,
                classifications
            )

            request_obj = {
                "key": sug_code,
                "request": {
                    "contents": [{"role": "user", "parts": [{"text": user_prompt}]}],
                    "systemInstruction": {"parts": [{"text": CRITIC_SYSTEM_PROMPT}]},
                    "generationConfig": {
                        "maxOutputTokens": 8192,
                        "thinking_config": {
                            "thinking_budget": THINKING_BUDGET
                        }
                    }
                }
            }

            f.write(json.dumps(request_obj) + "\n")
            request_count += 1

    if skipped:
        logger.warning(f"Skipped {len(skipped)} occupations:")
        for code, reason in skipped[:10]:
            logger.warning(f"  {code}: {reason}")

    return request_count


# Generate batch requests
n_requests = generate_critic_batch_requests(desc_df, tasks_df, class_df, BATCH_REQUESTS_FILE)
file_size_mb = BATCH_REQUESTS_FILE.stat().st_size / (1024 * 1024)

print(f"\nGenerated: {BATCH_REQUESTS_FILE}")
print(f"Requests: {n_requests}")
print(f"File size: {file_size_mb:.2f} MB")

"""# CELL 5: Upload and Submit Batch Job"""

# =============================================================================
# CELL 5: Upload and Submit Batch Job
# =============================================================================

# Check for existing job
if JOB_STATE_FILE.exists():
    with open(JOB_STATE_FILE, 'r') as f:
        existing = json.load(f)
    print(f"⚠️  Existing job: {existing.get('job_name')}")
    print(f"   Submitted: {existing.get('submitted_at')}")
    print("   Delete job_state file or rename to submit new job")
else:
    # Upload file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    print(f"Uploading: {BATCH_REQUESTS_FILE.name}")

    uploaded_file = client.files.upload(
        file=str(BATCH_REQUESTS_FILE),
        config=types.UploadFileConfig(
            display_name=f"gaisi_critic_{timestamp}",
            mime_type="jsonl"
        )
    )
    print(f"Uploaded: {uploaded_file.name}")

    # Create batch job
    print(f"Creating batch job with model: {MODEL_ID}")
    batch_job = client.batches.create(
        model=MODEL_ID,
        src=uploaded_file.name,
        config={'display_name': f"gaisi_critic_{timestamp}"}
    )

    # Save job state
    job_info = {
        'job_name': batch_job.name,
        'model': MODEL_ID,
        'n_requests': n_requests,
        'submitted_at': datetime.now().isoformat(),
        'state': str(batch_job.state),
        'uploaded_file': uploaded_file.name
    }

    with open(JOB_STATE_FILE, 'w') as f:
        json.dump(job_info, f, indent=2)

    print(f"\n✅ Batch job submitted: {batch_job.name}")
    print(f"   State: {batch_job.state}")
    print(f"   Job state saved to: {JOB_STATE_FILE.name}")

"""# CELL 6: Check Job Status"""

# =============================================================================
# CELL 6: Check Job Status
# =============================================================================

with open(JOB_STATE_FILE, 'r') as f:
    job_info = json.load(f)

job_name = job_info['job_name']
batch_job = client.batches.get(name=job_name)

print(f"Job: {job_name}")
print(f"State: {batch_job.state.name}")
print(f"Submitted: {job_info['submitted_at']}")

"""# CELL 7: Poll Until Complete"""

# =============================================================================
# CELL 7: Poll Until Complete
# =============================================================================

COMPLETED_STATES = {'JOB_STATE_SUCCEEDED', 'JOB_STATE_FAILED', 'JOB_STATE_CANCELLED', 'JOB_STATE_EXPIRED'}
POLL_INTERVAL = 60  # seconds

job_name = job_info['job_name']
print(f"Polling job: {job_name}")

while True:
    batch_job = client.batches.get(name=job_name)
    if batch_job.state.name in COMPLETED_STATES:
        break
    print(f"State: {batch_job.state.name}. Waiting {POLL_INTERVAL}s...")
    time.sleep(POLL_INTERVAL)

print(f"\n✅ Job finished: {batch_job.state.name}")

if batch_job.state.name == 'JOB_STATE_FAILED':
    print(f"Error: {batch_job.error}")

"""# CELL 8: Download Results"""

# =============================================================================
# CELL 8: Download Results
# =============================================================================

if batch_job.state.name == 'JOB_STATE_SUCCEEDED':
    result_file_name = batch_job.dest.file_name
    print(f"Downloading: {result_file_name}")

    content = client.files.download(file=result_file_name)

    with open(RESULTS_FILE, 'wb') as f:
        f.write(content)

    # Count results
    n_success = 0
    n_error = 0
    for line in content.decode('utf-8').splitlines():
        if not line.strip():
            continue
        result = json.loads(line)
        if 'response' in result and result['response']:
            n_success += 1
        elif 'error' in result:
            n_error += 1

    print(f"\n✅ Results saved: {RESULTS_FILE}")
    print(f"   Successful: {n_success}")
    print(f"   Errors: {n_error}")
else:
    print(f"Job not successful: {batch_job.state.name}")

"""# CELL 9: Parse Critic Results"""

# =============================================================================
# CELL 9: Parse Critic Results
# =============================================================================

def extract_response_text(result: dict) -> str:
    """Extract text from batch result, skipping thinking tokens."""
    if not result.get('response'):
        return ""

    try:
        parts = result['response']['candidates'][0]['content']['parts']
        for part in parts:
            if 'text' in part:
                return part['text']
    except (KeyError, IndexError):
        pass
    return ""


def parse_critic_row(line: str) -> dict:
    """Parse a single CSV row from critic output."""
    line = line.strip()
    if not line or line.startswith('#') or line.startswith('soccode'):
        return None

    # Remove markdown artifacts
    if line.startswith('```') or line.startswith('---'):
        return None

    # Pattern: sugcode, taskid, confidence, "critique"
    # Confidence is 0 or 1
    match = re.match(
        r'([^,]+),\s*([^,]+),\s*([01](?:\.0)?),\s*["\']?(.+?)["\']?\s*$',
        line
    )

    if match:
        return {
            'sugcode': match.group(1).strip(),
            'taskid': match.group(2).strip(),
            'critic_confidence': int(float(match.group(3).strip())),
            'critic_critique': match.group(4).strip()
        }

    # Fallback: simple split
    parts = line.split(',')
    if len(parts) >= 4:
        try:
            confidence = int(float(parts[2].strip()))
        except ValueError:
            confidence = -1  # Parse error marker

        return {
            'sugcode': parts[0].strip(),
            'taskid': parts[1].strip(),
            'critic_confidence': confidence,
            'critic_critique': ','.join(parts[3:]).strip().strip('"\'')
        }

    return None


def parse_critic_results(results_file: Path, output_file: Path):
    """Parse critic batch results to CSV."""

    all_rows = []
    errors = []

    with open(results_file, 'r') as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip():
                continue

            result = json.loads(line)
            sug_code = result.get('key', f'unknown_{line_num}')

            if result.get('error'):
                errors.append({'sug_code': sug_code, 'error': result['error']})
                continue

            text = extract_response_text(result)
            if not text:
                errors.append({'sug_code': sug_code, 'error': 'Empty response'})
                continue

            occupation_rows = 0
            for output_line in text.splitlines():
                parsed = parse_critic_row(output_line)
                if parsed:
                    all_rows.append(parsed)
                    occupation_rows += 1

            if occupation_rows == 0:
                errors.append({'sug_code': sug_code, 'error': 'No parseable rows'})

    # Write CSV
    with open(output_file, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['sugcode', 'taskid', 'critic_confidence', 'critic_critique'])
        writer.writeheader()
        writer.writerows(all_rows)

    return len(all_rows), errors


# Parse critic results
n_rows, errors = parse_critic_results(RESULTS_FILE, PARSED_CRITIC_FILE)

print(f"✅ Parsed {n_rows} critic reviews to: {PARSED_CRITIC_FILE.name}")

if errors:
    print(f"\n⚠️  {len(errors)} occupations had errors:")
    for e in errors[:10]:
        print(f"   {e['sug_code']}: {e['error']}")
    if len(errors) > 10:
        print(f"   ... and {len(errors) - 10} more")

"""# CELL 10: Merge Classifications with Critic Reviews"""

# =============================================================================
# CELL 10: Merge Classifications with Critic Reviews
# =============================================================================

def merge_classifications_and_reviews(class_file: Path, critic_file: Path,
                                       output_file: Path) -> pd.DataFrame:
    """Merge original classifications with critic reviews."""

    # Load both files
    class_df = pd.read_csv(class_file, dtype=str)
    critic_df = pd.read_csv(critic_file, dtype=str)

    # Standardize columns
    class_df.columns = class_df.columns.str.strip().str.lower()
    critic_df.columns = critic_df.columns.str.strip().str.lower()

    # Clean keys
    class_df['sugcode'] = class_df['sugcode'].str.strip()
    class_df['taskid'] = class_df['taskid'].str.strip()
    critic_df['sugcode'] = critic_df['sugcode'].str.strip()
    critic_df['taskid'] = critic_df['taskid'].str.strip()

    # Merge
    merged = class_df.merge(
        critic_df[['sugcode', 'taskid', 'critic_confidence', 'critic_critique']],
        on=['sugcode', 'taskid'],
        how='left'
    )

    # Report merge stats
    n_matched = merged['critic_confidence'].notna().sum()
    n_missing = merged['critic_confidence'].isna().sum()

    print(f"Classifications: {len(class_df)}")
    print(f"Critic reviews: {len(critic_df)}")
    print(f"Matched: {n_matched}")
    print(f"Missing reviews: {n_missing}")

    # Fill missing
    merged['critic_confidence'] = merged['critic_confidence'].fillna('-1')
    merged['critic_critique'] = merged['critic_critique'].fillna('Review missing')

    # Save
    merged.to_csv(output_file, index=False)

    return merged


# Merge
merged_df = merge_classifications_and_reviews(
    CLASSIFICATIONS_FILE,
    PARSED_CRITIC_FILE,
    FINAL_MERGED_FILE
)

print(f"\n✅ Final merged file: {FINAL_MERGED_FILE.name}")
print(f"   Total rows: {len(merged_df)}")

"""# CELL 11: Summary Statistics"""

# =============================================================================
# CELL 11: Summary Statistics
# =============================================================================

# Convert confidence to numeric for analysis
merged_df['critic_confidence'] = pd.to_numeric(merged_df['critic_confidence'], errors='coerce')

# Summary
print("\n" + "="*60)
print("CRITIC REVIEW SUMMARY")
print("="*60)

valid_reviews = merged_df[merged_df['critic_confidence'].isin([0, 1])]

if len(valid_reviews) > 0:
    n_defensible = (valid_reviews['critic_confidence'] == 1).sum()
    n_flagged = (valid_reviews['critic_confidence'] == 0).sum()

    print(f"\nTotal reviewed: {len(valid_reviews)}")
    print(f"Defensible (confidence=1): {n_defensible} ({100*n_defensible/len(valid_reviews):.1f}%)")
    print(f"Flagged (confidence=0): {n_flagged} ({100*n_flagged/len(valid_reviews):.1f}%)")

    # Breakdown by occupation
    occ_summary = valid_reviews.groupby('sugcode').agg({
        'critic_confidence': ['count', 'sum', 'mean']
    }).round(2)
    occ_summary.columns = ['n_tasks', 'n_defensible', 'pct_defensible']
    occ_summary = occ_summary.sort_values('pct_defensible')

    print(f"\n--- Occupations with most flagged tasks ---")
    print(occ_summary.head(10))

    # Sample flagged critiques
    flagged = valid_reviews[valid_reviews['critic_confidence'] == 0]
    if len(flagged) > 0:
        print(f"\n--- Sample flagged critiques ---")
        for _, row in flagged.head(5).iterrows():
            print(f"  [{row['sugcode']}/{row['taskid']}]: {row['critic_critique'][:100]}")

print("\nPreview:")
print(merged_df.head(10))