# -*- coding: utf-8 -*-
"""GAISI_SSC_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PCSDbuV8aoTO71MJ8I316Az8rrzel1u

# Setup and Configuration
"""

"""
GAISI Classification Pipeline - Gemini Batch API
Run each section as a separate Colab cell.
"""

# =============================================================================
# CELL 1: Setup and Configuration
# =============================================================================

# Install SDK (uncomment if needed)
# !pip install -q -U "google-genai>=1.34.0"

import json
import time
import logging
import csv
import re
from pathlib import Path
import pandas as pd

from google.colab import drive, userdata
from google import genai
from google.genai import types

# Mount drive and set paths
drive.mount('/content/drive')
BASE_PATH = Path('/content/drive/My Drive/AI_CLASSIFICATION')
INPUT_DIR = BASE_PATH / "Inputs"
OUTPUT_DIR = BASE_PATH / "Outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# File paths
DESCRIPTIONS_FILE = INPUT_DIR / "sug_codes_descriptions.clean.csv"
TASKS_FILE = INPUT_DIR / "sugs_to_tasks.csv"
BATCH_REQUESTS_FILE = OUTPUT_DIR / "batch_requests.jsonl"
JOB_STATE_FILE = OUTPUT_DIR / "batch_job_state_1030_20251230.json"
RESULTS_FILE = OUTPUT_DIR / "batch_results_1030_20251230.jsonl"
PARSED_CSV_FILE = OUTPUT_DIR / "gaisi_classifications.csv"

# Column mappings (update if your files differ)
DESC_COLS = {'code': 'sugcode', 'title': 'sugtitle', 'description': 'sugdescription'}
TASK_COLS = {'code': 'sugcode', 'id': 'taskid', 'statement': 'task'}

# Model config
MODEL_ID = "gemini-2.5-pro"
THINKING_BUDGET = 1200

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(message)s")
logger = logging.getLogger(__name__)

# Initialize client
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY_1')
client = genai.Client(api_key=GOOGLE_API_KEY)

print(f"Model: {MODEL_ID}")
print(f"Thinking budget: {THINKING_BUDGET}")
print(f"Input dir: {INPUT_DIR}")
print(f"Output dir: {OUTPUT_DIR}")

"""# System Prompt"""

# =============================================================================
# CELL 2: System Prompt
# =============================================================================

SYSTEM_PROMPT = """You are an expert AI evaluation tool. Your purpose is to analyze job tasks and determine their susceptibility to augmentation by Large Language Models (LLMs).

You will be given <occupation_details>. The tasks to classify are wrapped in the <task_list> tag.

## Instruction:
For each task, follow this process to arrive at a set of exposure probabilities:
1.  **Contextualize**: Briefly explain what performing this task entails for a worker in the specified occupation.
2.  **Existing Tools:** Consider how an average worker in this occupation would perform each task using existing non-AI software or hardware tools.
3.  **Analyze LLM Potential**: Assess how an LLM could reduce the time to complete the task by at least 25%. Consider direct use, E1, (e.g., text generation, knowledge synthesis, analysis), integrated use, E2, (e.g., an 'AI assistant' in an app), or image analysis capabilities, E3. Focus on LLM capabilities beyond existing tools, such as text generation, analysis, knowledge synthesis, or planning and scheduling in isolation or combined.
4.  **Probability Distribution**: Assign a probability to each of the four exposure levels (E0, E1, E2, E3). The probabilities must sum to 1.0.
5.  **Justification**: Provide a clear justification for your chosen distribution, describing the central mechanism.

## Exposure Levels:
-   **E0: No Exposure**: LLMs are unlikely to reduce task completion time by 25%. Existing tools are highly efficient, or the task is inherently physical, interpersonal, or requires high-stakes human judgment.
-   **E1: Direct Exposure**: Using an LLM via a chat interface or console (e.g. ChatGPT or Open AI playground) can decrease the time required to complete the task by at 25%.
-   **E2: Integrated Exposure**: An LLM integrated into other software (e.g., an "AI assistant" or "Co-pilot" in a specific application) or hardware (robotics) can reduce task time by 25% or more.
-   **E3: Image Exposure**: LLM-based image generation or analysis can reduce task time by at least 25%.

YOU MUST provide your response as a rectangular object with a row per task and comma-separated values in columns. Each row includes the occupation code, task ID, the probabilities and a brief justification. The justification is free of any punctuation.

## Output: sugcode, taskid, e0, e1, e2, e3, justification
```
{sugcode}, {taskid1}, 0.xx, 0.xx, 0.xx, 0.xx, "One sentence justification for probabilities"
{sugcode}, {taskid2}, 0.xx, 0.xx, 0.xx, 0.xx, "One sentence justification for probabilities"
'''
Do not include a header row. Output ONLY the data rows; NOTHING else.
"""

print(f"System prompt: {len(SYSTEM_PROMPT)} characters")

# =============================================================================
# CELL 2B: Clean Non-UTF-8 Characters from Source Files
# =============================================================================

def find_and_clean_encoding_issues(filepath: Path, preview_only: bool = True):
    """
    Find non-UTF-8 bytes in a file and optionally clean them.

    Args:
        filepath: Path to the file
        preview_only: If True, just report issues. If False, create cleaned file.
    """

    print(f"\nChecking: {filepath.name}")

    # Read as binary
    with open(filepath, 'rb') as f:
        raw_bytes = f.read()

    issues = []

    # Try to decode, tracking problem positions
    i = 0
    while i < len(raw_bytes):
        # Try decoding from this position
        try:
            # Check if this byte starts a valid UTF-8 sequence
            if raw_bytes[i] < 128:
                # ASCII - always valid
                i += 1
            elif raw_bytes[i] < 192:
                # Continuation byte without start - invalid
                issues.append((i, raw_bytes[i:i+1]))
                i += 1
            elif raw_bytes[i] < 224:
                # 2-byte sequence
                raw_bytes[i:i+2].decode('utf-8')
                i += 2
            elif raw_bytes[i] < 240:
                # 3-byte sequence
                raw_bytes[i:i+3].decode('utf-8')
                i += 3
            elif raw_bytes[i] < 248:
                # 4-byte sequence
                raw_bytes[i:i+4].decode('utf-8')
                i += 4
            else:
                # Invalid start byte
                issues.append((i, raw_bytes[i:i+1]))
                i += 1
        except (UnicodeDecodeError, IndexError):
            issues.append((i, raw_bytes[i:i+1]))
            i += 1

    if not issues:
        print(f"  ✅ No encoding issues found")
        return

    print(f"  ⚠️  Found {len(issues)} problematic byte(s)")

    # Show context for each issue
    for pos, bad_byte in issues[:20]:  # Show first 20
        # Get surrounding context
        start = max(0, pos - 30)
        end = min(len(raw_bytes), pos + 30)

        # Decode context with replacement
        before = raw_bytes[start:pos].decode('utf-8', errors='replace')
        after = raw_bytes[pos+1:end].decode('utf-8', errors='replace')

        print(f"  Position {pos}: byte 0x{bad_byte.hex()} | ...{before[-20:]}[?]{after[:20]}...")

    if len(issues) > 20:
        print(f"  ... and {len(issues) - 20} more")

    if preview_only:
        print(f"\n  Run with preview_only=False to create cleaned file")
        return

    # Create cleaned version
    cleaned = raw_bytes.decode('utf-8', errors='replace')  # Replace bad bytes with �
    # Or remove entirely:
    # cleaned = raw_bytes.decode('utf-8', errors='ignore')

    clean_path = filepath.with_suffix('.clean.csv')
    with open(clean_path, 'w', encoding='utf-8') as f:
        f.write(cleaned)

    print(f"  ✅ Cleaned file saved: {clean_path.name}")
    print(f"     (Bad bytes replaced with '�' - review and fix manually if needed)")

    return clean_path


# Check both files (preview only first)
find_and_clean_encoding_issues(DESCRIPTIONS_FILE, preview_only=True)
find_and_clean_encoding_issues(TASKS_FILE, preview_only=True)

# Once you've reviewed, run with preview_only=False:
# find_and_clean_encoding_issues(DESCRIPTIONS_FILE, preview_only=False)
# find_and_clean_encoding_issues(TASKS_FILE, preview_only=False)

"""# Load and Prepare Data"""

# =============================================================================
# CELL 3: Load and Prepare Data
# =============================================================================

def load_data():
    """Load and merge occupation descriptions with tasks."""

    # Load descriptions
    logger.info(f"Loading: {DESCRIPTIONS_FILE.name}")
    desc_df = pd.read_csv(DESCRIPTIONS_FILE, dtype=str)
    desc_df = desc_df.rename(columns={
        DESC_COLS['code']: 'sug_code',
        DESC_COLS['title']: 'title',
        DESC_COLS['description']: 'description'
    })
    desc_df['sug_code'] = desc_df['sug_code'].str.strip()

    # Load tasks
    logger.info(f"Loading: {TASKS_FILE.name}")
    tasks_df = pd.read_csv(TASKS_FILE, dtype=str)
    tasks_df = tasks_df.rename(columns={
        TASK_COLS['code']: 'sug_code',
        TASK_COLS['id']: 'task_id',
        TASK_COLS['statement']: 'task_statement'
    })
    tasks_df['sug_code'] = tasks_df['sug_code'].str.strip()

    # Merge
    merged = desc_df.merge(tasks_df, on='sug_code', how='inner')

    logger.info(f"Merged: {len(merged)} task-occupation pairs, {merged['sug_code'].nunique()} occupations")

    return merged

# Load data
merged_df = load_data()
print(f"\nSample:\n{merged_df.head()}")

"""# Generate Batch Requests JSONL"""

# =============================================================================
# CELL 4: Generate Batch Requests JSONL
# =============================================================================

def build_prompt(sug_code: str, title: str, description: str, tasks: list) -> str:
    """Build user prompt for a single occupation."""
    occupation_block = f"""occupation_code: {sug_code}
occupation_title: {title}
occupation_description: {description}"""

    task_lines = "\n".join(f"{t['task_id']}\t{t['task_statement']}" for t in tasks)

    return (
        f"<occupation_details>\n{occupation_block}\n</occupation_details>\n\n"
        f"<task_list>\n{task_lines}\n</task_list>"
    )


def generate_batch_requests(df: pd.DataFrame, output_path: Path) -> int:
    """Generate JSONL file with batch requests."""

    request_count = 0

    with open(output_path, 'w') as f:
        for sug_code, group in df.groupby('sug_code'):
            row = group.iloc[0]
            tasks = [
                {'task_id': r['task_id'], 'task_statement': r['task_statement']}
                for _, r in group.iterrows()
            ]

            user_prompt = build_prompt(sug_code, row['title'], row['description'], tasks)

            request_obj = {
                "key": sug_code,
                "request": {
                    "contents": [{"role": "user", "parts": [{"text": user_prompt}]}],
                    "systemInstruction": {"parts": [{"text": SYSTEM_PROMPT}]},
                    "generationConfig": {
                        "maxOutputTokens": 8192,
                        "thinking_config": {
                            "thinking_budget": THINKING_BUDGET
                        }
                    }
                }
            }

            f.write(json.dumps(request_obj) + "\n")
            request_count += 1

    return request_count


# Generate JSONL
n_requests = generate_batch_requests(merged_df, BATCH_REQUESTS_FILE)
file_size_mb = BATCH_REQUESTS_FILE.stat().st_size / (1024 * 1024)

print(f"Generated: {BATCH_REQUESTS_FILE}")
print(f"Requests: {n_requests}")
print(f"File size: {file_size_mb:.2f} MB")
print(f"Total tasks: {len(merged_df)}")

"""# Upload File and Submit Batch Job"""

# =============================================================================
# CELL 5: Upload File and Submit Batch Job
# =============================================================================

from datetime import datetime

# Check for existing job
if JOB_STATE_FILE.exists():
    with open(JOB_STATE_FILE, 'r') as f:
        existing = json.load(f)
    print(f"⚠️  Existing job: {existing.get('job_name')}")
    print(f"   Submitted: {existing.get('submitted_at')}")
    print("   Delete job_state file or rename to submit new job")
else:
    # Upload file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    print(f"Uploading: {BATCH_REQUESTS_FILE.name}")

    uploaded_file = client.files.upload(
        file=str(BATCH_REQUESTS_FILE),
        config=types.UploadFileConfig(
            display_name=f"gaisi_batch_{timestamp}",
            mime_type="jsonl"
        )
    )
    print(f"Uploaded: {uploaded_file.name}")

    # Create batch job
    print(f"Creating batch job with model: {MODEL_ID}")
    batch_job = client.batches.create(
        model=MODEL_ID,
        src=uploaded_file.name,
        config={'display_name': f"gaisi_{timestamp}"}
    )

    # Save job state
    job_info = {
        'job_name': batch_job.name,
        'model': MODEL_ID,
        'n_requests': n_requests,
        'submitted_at': datetime.now().isoformat(),
        'state': str(batch_job.state),
        'uploaded_file': uploaded_file.name
    }

    with open(JOB_STATE_FILE, 'w') as f:
        json.dump(job_info, f, indent=2)

    print(f"\n✅ Batch job submitted: {batch_job.name}")
    print(f"   State: {batch_job.state}")
    print(f"   Job state saved to: {JOB_STATE_FILE.name}")

"""# Check Job Status"""

# =============================================================================
# CELL 6: Check Job Status
# =============================================================================

# Load job info
with open(JOB_STATE_FILE, 'r') as f:
    job_info = json.load(f)

job_name = job_info['job_name']
batch_job = client.batches.get(name=job_name)

print(f"Job: {job_name}")
print(f"State: {batch_job.state.name}")
print(f"Submitted: {job_info['submitted_at']}")

"""# Poll Until Complete"""

# =============================================================================
# CELL 7: Poll Until Complete (Optional - run if not yet complete)
# =============================================================================

COMPLETED_STATES = {'JOB_STATE_SUCCEEDED', 'JOB_STATE_FAILED', 'JOB_STATE_CANCELLED', 'JOB_STATE_EXPIRED'}
POLL_INTERVAL = 60  # seconds

job_name = job_info['job_name']
print(f"Polling job: {job_name}")

while True:
    batch_job = client.batches.get(name=job_name)
    if batch_job.state.name in COMPLETED_STATES:
        break
    print(f"State: {batch_job.state.name}. Waiting {POLL_INTERVAL}s...")
    time.sleep(POLL_INTERVAL)

print(f"\n✅ Job finished: {batch_job.state.name}")

if batch_job.state.name == 'JOB_STATE_FAILED':
    print(f"Error: {batch_job.error}")

"""# Download Results"""

# =============================================================================
# CELL 8: Download Results
# =============================================================================

if batch_job.state.name == 'JOB_STATE_SUCCEEDED':
    result_file_name = batch_job.dest.file_name
    print(f"Downloading: {result_file_name}")

    content = client.files.download(file=result_file_name)

    with open(RESULTS_FILE, 'wb') as f:
        f.write(content)

    # Count results
    n_success = 0
    n_error = 0
    for line in content.decode('utf-8').splitlines():
        if not line.strip():
            continue
        result = json.loads(line)
        if 'response' in result and result['response']:
            n_success += 1
        elif 'error' in result:
            n_error += 1

    print(f"\n✅ Results saved: {RESULTS_FILE}")
    print(f"   Successful: {n_success}")
    print(f"   Errors: {n_error}")
else:
    print(f"Job not successful: {batch_job.state.name}")

"""# Preview Results"""

# =============================================================================
# CELL 9: Preview Results (Optional)
# =============================================================================

# Preview first few results
with open(RESULTS_FILE, 'r') as f:
    for i, line in enumerate(f):
        if i >= 3:  # Show first 3
            break
        if line.strip():
            result = json.loads(line)
            print(f"\n--- {result.get('key', 'unknown')} ---")
            if result.get('response'):
                try:
                    text = result['response']['candidates'][0]['content']['parts'][0]['text']
                    print(text[:500] + "..." if len(text) > 500 else text)
                except (KeyError, IndexError):
                    print(json.dumps(result['response'], indent=2)[:500])
            elif result.get('error'):
                print(f"Error: {result['error']}")

# =============================================================================
# CELL 10: Parse Results to Flat CSV
# =============================================================================

def extract_response_text(result: dict) -> str:
    """Extract text from batch result, skipping thinking tokens."""
    if not result.get('response'):
        return ""

    try:
        parts = result['response']['candidates'][0]['content']['parts']
        # Find the text part (skip thinking parts if present)
        for part in parts:
            if 'text' in part:
                return part['text']
    except (KeyError, IndexError):
        pass
    return ""


def parse_classification_row(line: str) -> dict:
    """Parse a single CSV row from model output."""
    # Clean up the line
    line = line.strip()
    if not line or line.startswith('#') or line.startswith('sug_code'):
        return None

    # Remove markdown code block markers if present
    if line.startswith('```') or line.startswith('---'):
        return None

    # Split by comma, handling quoted justification
    # Pattern: sug_code, task_id, e0, e1, e2, e3, "justification"
    match = re.match(
        r'([^,]+),\s*([^,]+),\s*([0-9.]+),\s*([0-9.]+),\s*([0-9.]+),\s*([0-9.]+),\s*["\']?(.+?)["\']?\s*$',
        line
    )

    if match:
        return {
            'sugcode': match.group(1).strip(),
            'taskid': match.group(2).strip(),
            'e0': match.group(3).strip(),
            'e1': match.group(4).strip(),
            'e2': match.group(5).strip(),
            'e3': match.group(6).strip(),
            'justification': match.group(7).strip()
        }

    # Fallback: simple split (may fail on commas in justification)
    parts = line.split(',')
    if len(parts) >= 7:
        return {
            'sugcode': parts[0].strip(),
            'taskid': parts[1].strip(),
            'e0': parts[2].strip(),
            'e1': parts[3].strip(),
            'e2': parts[4].strip(),
            'e3': parts[5].strip(),
            'justification': ','.join(parts[6:]).strip().strip('"\'')
        }

    return None


def parse_results_to_csv(results_file: Path, output_file: Path):
    """Parse batch results JSONL to flat CSV."""

    all_rows = []
    errors = []

    with open(results_file, 'r') as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip():
                continue

            result = json.loads(line)
            sug_code = result.get('key', f'unknown_{line_num}')

            # Check for errors
            if result.get('error'):
                errors.append({'sug_code': sug_code, 'error': result['error']})
                continue

            # Extract and parse response text
            text = extract_response_text(result)
            if not text:
                errors.append({'sug_code': sug_code, 'error': 'Empty response'})
                continue

            # Parse each line of the CSV output
            occupation_rows = 0
            for output_line in text.splitlines():
                parsed = parse_classification_row(output_line)
                if parsed:
                    all_rows.append(parsed)
                    occupation_rows += 1

            if occupation_rows == 0:
                errors.append({'sug_code': sug_code, 'error': 'No parseable rows'})

    # Write CSV
    with open(output_file, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['sugcode', 'taskid', 'e0', 'e1', 'e2', 'e3', 'justification'])
        writer.writeheader()
        writer.writerows(all_rows)

    return len(all_rows), errors


# Parse results
n_rows, errors = parse_results_to_csv(RESULTS_FILE, PARSED_CSV_FILE)

print(f"✅ Parsed {n_rows} task classifications to: {PARSED_CSV_FILE.name}")

if errors:
    print(f"\n⚠️  {len(errors)} occupations had errors:")
    for e in errors[:10]:  # Show first 10
        print(f"   {e['sug_code']}: {e['error']}")
    if len(errors) > 10:
        print(f"   ... and {len(errors) - 10} more")

# Preview
print(f"\nPreview:")
preview_df = pd.read_csv(PARSED_CSV_FILE)
print(preview_df.head(10))
print(f"\nTotal rows: {len(preview_df)}")